initFields:
  version: 0.0.1
  author: mlnck
  description: quarx
  downquarkDir: ~/.dqrx
  homepage: downquark.work
  license: GNU
  main: .js

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

progressBarStyle: simba
# ## Remove tht following line when typescript works with finding the correct import
# ## > - Toggle below, run `% yarn`, and see `_sqeleton/qore/_qomponents/atomic/1.atoms/timeline.ts` for an example
# ## > > - will have to `% rm -rf node_modules` when actual solution is found
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.2.cjs
